Adding post factum version 2.1.6
git-svn-id: https://svn.iu.hio.no/projects/cfengine-2/trunk@12 0bacebff-10ef-0310-a86f-bc4055e020e4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS PTHREAD_CPPFLAGS LEX LEXLIB LEX_OUTPUT_ROOT YACC RANLIB ac_ct_RANLIB LIBOBJS CPP EGREP NEED_SETGID KMEM_GROUP GETLOADAVG_LIBS LATEX TEXI2DVI DVIPS PS2PDF BERKELEY_DB_LDFLAGS BERKELEY_DB_CFLAGS BERKELEY_DB_LIB OPENSSL_LIB_LDFLAGS OPENSSL_LIB_CPPFLAGS OPENSSL_LIB_LIB EIGHTBIT NOWRAP GCC_CFLAG HOSTNAME LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS PTHREAD_CPPFLAGS LEX LEXLIB LEX_OUTPUT_ROOT YACC RANLIB ac_ct_RANLIB LIBOBJS CPP EGREP NEED_SETGID KMEM_GROUP GETLOADAVG_LIBS LATEX TEXI2DVI DVIPS PS2PDF BERKELEY_DB_LDFLAGS BERKELEY_DB_CFLAGS BERKELEY_DB_LIB OPENSSL_LIB_LDFLAGS OPENSSL_LIB_CPPFLAGS OPENSSL_LIB_LIB EIGHTBIT NOWRAP GCC_CFLAG HOSTNAME BUILD_DOC_TRUE BUILD_DOC_FALSE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -861,6 +861,7 @@ Optional Packages:
   --with-berkeleydb=PATH directory where BerkeleyDB exists
   --with-openssl=PATH directory where OpenSSL exists
   --with-workdir=WORKDIR  default internal for trusted cache
+  --with-docs          build the documentation
 
 Some influential environment variables:
   CC          C compiler command
@@ -1692,7 +1693,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=cfengine
- VERSION=2.1.5
+ VERSION=2.1.6
 
 
 cat >>confdefs.h <<_ACEOF
@@ -15717,6 +15718,25 @@ _ACEOF
 
 
 
+
+# Check whether --with-docs or --without-docs was given.
+if test "${with_docs+set}" = set; then
+  withval="$with_docs"
+   want_doc=true
+else
+   want_doc=false
+fi;
+
+
+if test x$want_doc = xtrue; then
+  BUILD_DOC_TRUE=
+  BUILD_DOC_FALSE='#'
+else
+  BUILD_DOC_TRUE='#'
+  BUILD_DOC_FALSE=
+fi
+
+
                                                                                 ac_config_files="$ac_config_files pub/Makefile src/Makefile contrib/Makefile inputs/Makefile Makefile doc/Makefile src/cflex.l contrib/vicf"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -15827,6 +15847,13 @@ if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_DOC_TRUE}" && test -z "${BUILD_DOC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_DOC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_DOC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -16447,6 +16474,8 @@ s,@EIGHTBIT@,$EIGHTBIT,;t t
 s,@NOWRAP@,$NOWRAP,;t t
 s,@GCC_CFLAG@,$GCC_CFLAG,;t t
 s,@HOSTNAME@,$HOSTNAME,;t t
+s,@BUILD_DOC_TRUE@,$BUILD_DOC_TRUE,;t t
+s,@BUILD_DOC_FALSE@,$BUILD_DOC_FALSE,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
