Adding post factum version 2.1.7p1
git-svn-id: https://svn.iu.hio.no/projects/cfengine-2/trunk@13 0bacebff-10ef-0310-a86f-bc4055e020e4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1693,7 +1693,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=cfengine
- VERSION=2.1.6
+ VERSION=2.1.7p1
 
 
 cat >>confdefs.h <<_ACEOF
@@ -13171,6 +13171,69 @@ _ACEOF
 fi
 done
 
+
+
+echo "$as_me:$LINENO: checking for sa_len in struct sockaddr" >&5
+echo $ECHO_N "checking for sa_len in struct sockaddr... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <sys/types.h>
+#include <sys/socket.h>
+
+int
+main ()
+{
+
+struct sockaddr sa;
+int foo = sa.sa_len;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_struct_sockaddr_sa_len=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_struct_sockaddr_sa_len=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+if test "$ac_cv_struct_sockaddr_sa_len" = yes; then
+   cat >>confdefs.h <<\_ACEOF
+#define SOCKADDR_HAS_SA_LEN 1
+_ACEOF
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_struct_sockaddr_sa_len" >&5
+echo "${ECHO_T}$ac_cv_struct_sockaddr_sa_len" >&6
 
 
 rtry=none
