Rewritten the checksum database subsystem
git-svn-id: https://svn.iu.hio.no/projects/cfengine-2/trunk@285 0bacebff-10ef-0310-a86f-bc4055e020e4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1702,7 +1702,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=cfengine
- VERSION=2.1.21
+ VERSION=2.1.22a
 
 
 cat >>confdefs.h <<_ACEOF
@@ -8322,12 +8322,12 @@ echo $ECHO_N "checking for BerkeleyDB location in $BERKELEY_DB_DIR... $ECHO_C" >
 if test "x$BERKELEY_DB_DIR" = "xno" ; then
     echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6
-    { { echo "$as_me:$LINENO: error: This release of cfengine requires a version of BerkeleyDB 3.2 or later" >&5
-echo "$as_me: error: This release of cfengine requires a version of BerkeleyDB 3.2 or later" >&2;}
+    { { echo "$as_me:$LINENO: error: This release of cfengine requires a version of BerkeleyDB 4.4 or later" >&5
+echo "$as_me: error: This release of cfengine requires a version of BerkeleyDB 4.4 or later" >&2;}
    { (exit 1); exit 1; }; }
 else
     if test "x$BERKELEY_DB_DIR" = "xdefault" ; then
-        for v in BerkeleyDB.3.2 BerkeleyDB.3.3 BerkeleyDB.4.0  BerkeleyDB.4.1  BerkeleyDB.4.2 BerkeleyDB.4.3 BerkeleyDB.4.4; do
+        for v in BerkeleyDB.4.2 BerkeleyDB.4.3 BerkeleyDB.4.4 BerkeleyDB.4.5 BerkeleyDB.4.6; do
             for d in $prefix /opt /usr/local /usr; do
                 test -d "$d/$v" && BERKELEY_DB_DIR="$d/$v"
             done
@@ -17557,8 +17557,8 @@ echo "$as_me: WARNING: " >&2;}
 echo "$as_me: WARNING: DFS users should use --enable-DCE" >&2;}
 { echo "$as_me:$LINENO: WARNING: " >&5
 echo "$as_me: WARNING: " >&2;}
-{ echo "$as_me:$LINENO: WARNING: This version requires Berkeley db version 3.2 or" >&5
-echo "$as_me: WARNING: This version requires Berkeley db version 3.2 or" >&2;}
+{ echo "$as_me:$LINENO: WARNING: This version requires Berkeley db version 4.4 or" >&5
+echo "$as_me: WARNING: This version requires Berkeley db version 4.4 or" >&2;}
 { echo "$as_me:$LINENO: WARNING: later from www.sleepycat.com" >&5
 echo "$as_me: WARNING: later from www.sleepycat.com" >&2;}
 { echo "$as_me:$LINENO: WARNING: This version requires OpenSSL 0.9.7 or later" >&5
