Adding post factum version 2.1.11
git-svn-id: https://svn.iu.hio.no/projects/cfengine-2/trunk@16 0bacebff-10ef-0310-a86f-bc4055e020e4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS PTHREAD_CPPFLAGS LEX LEXLIB LEX_OUTPUT_ROOT YACC RANLIB ac_ct_RANLIB LIBOBJS CPP EGREP NEED_SETGID KMEM_GROUP GETLOADAVG_LIBS LATEX TEXI2DVI DVIPS PS2PDF BERKELEY_DB_LDFLAGS BERKELEY_DB_CFLAGS BERKELEY_DB_LIB OPENSSL_LIB_LDFLAGS OPENSSL_LIB_CPPFLAGS OPENSSL_LIB_LIB EIGHTBIT NOWRAP GCC_CFLAG HOSTNAME BUILD_DOC_TRUE BUILD_DOC_FALSE LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS PTHREAD_CPPFLAGS LEX LEXLIB LEX_OUTPUT_ROOT YACC RANLIB ac_ct_RANLIB LIBOBJS CPP EGREP NEED_SETGID KMEM_GROUP GETLOADAVG_LIBS LATEX TEXI2DVI DVIPS PS2PDF GETCONF BERKELEY_DB_LDFLAGS BERKELEY_DB_CFLAGS BERKELEY_DB_LIB OPENSSL_LIB_LDFLAGS OPENSSL_LIB_CPPFLAGS OPENSSL_LIB_LIB EIGHTBIT NOWRAP GCC_CFLAG HOSTNAME BUILD_DOC_TRUE BUILD_DOC_FALSE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1693,7 +1693,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=cfengine
- VERSION=2.1.10
+ VERSION=2.1.11
 
 
 cat >>confdefs.h <<_ACEOF
@@ -7372,6 +7372,47 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+# Extract the first word of "getconf", so it can be a program name with args.
+set dummy getconf; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_GETCONF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GETCONF in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GETCONF="$GETCONF" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+as_dummy="$PATH:$prefix/bin:/usr/bin:/usr/local/bin:/sw/bin"
+for as_dir in $as_dummy
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_GETCONF="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_GETCONF" && ac_cv_path_GETCONF="false"
+  ;;
+esac
+fi
+GETCONF=$ac_cv_path_GETCONF
+
+if test -n "$GETCONF"; then
+  echo "$as_me:$LINENO: result: $GETCONF" >&5
+echo "${ECHO_T}$GETCONF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 
 
 
@@ -8249,10 +8290,12 @@ if test "${with_berkeleydb+set}" = set; then
   withval="$with_berkeleydb"
   BERKELEY_DB_DIR=$with_berkeleydb
 else
-  BERKELEY_DB_DIR=yes
+  BERKELEY_DB_DIR=default
 fi;
-echo "$as_me:$LINENO: checking for BerkeleyDB location" >&5
-echo $ECHO_N "checking for BerkeleyDB location... $ECHO_C" >&6
+
+echo "$as_me:$LINENO: checking for BerkeleyDB location in $BERKELEY_DB_DIR" >&5
+echo $ECHO_N "checking for BerkeleyDB location in $BERKELEY_DB_DIR... $ECHO_C" >&6
+
 if test "x$BERKELEY_DB_DIR" = "xno" ; then
     echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6
@@ -8260,24 +8303,28 @@ echo "${ECHO_T}" >&6
 echo "$as_me: error: This release of cfengine requires BerkeleyDB 3.2 or later" >&2;}
    { (exit 1); exit 1; }; }
 else
-    if test "x$BERKELEY_DB_DIR" = "xyes" ; then
+    if test "x$BERKELEY_DB_DIR" = "xdefault" ; then
         for v in BerkeleyDB.3.2 BerkeleyDB.3.3 BerkeleyDB.4.0  BerkeleyDB.4.1  BerkeleyDB.4.2 BerkeleyDB.4.3 BerkeleyDB.4.4; do
             for d in /opt /usr/local /usr; do
                 test -d "$d/$v" && BERKELEY_DB_DIR="$d/$v"
             done
         done
     fi
-    if test "x$BERKELEY_DB_DIR" = "xyes" ; then
+
+    if test "x$BERKELEY_DB_DIR" = "xdefault" ; then
+
         for d in /opt /usr/local /usr; do
-            for v in db-4 db4 db3 db; do
+            for v in db-4 db4 db3 db db40; do
+
                 if test -f "$d/include/$v/db.h" ; then
+                    echo "Found header in $d/include/$v "
                     test "x$d" != "x/usr" && BERKELEY_DB_LDFLAGS="-L$d/lib"
                     BERKELEY_DB_CFLAGS="-I$d/include/$v"
                     late_LIBS=$LIBS
 		    # In RedHat 8, for instance, we have /usr/include/db4
 		    # and libdb-4.0.a.  Debian has /usr/lib/libdb-4.1.a, for
 		    # instance.  Look for the appropriate library.
-                    if test $v = db4; then
+                    if test $v = db4 -o $v = db40; then
 			echo "$as_me:$LINENO: checking for library containing db_create" >&5
 echo $ECHO_N "checking for library containing db_create... $ECHO_C" >&6
 if test "${ac_cv_search_db_create+set}" = set; then
@@ -8413,6 +8460,7 @@ echo "${ECHO_T}$d" >&6
                     break
                 fi
             done
+
 	    test "x$BERKELEY_DB_LIB" != "x" && break
             if test -f "$d/include/db.h"; then
                 if test "x$d" != "x/usr"; then
@@ -8425,14 +8473,24 @@ echo "${ECHO_T}$d" >&6
                 break
             fi
 	done
+
         if test "x$BERKELEY_DB_LIB" = "x" ; then
             { { echo "$as_me:$LINENO: error: Cannot find BerkeleyDB" >&5
 echo "$as_me: error: Cannot find BerkeleyDB" >&2;}
    { (exit 1); exit 1; }; }
         fi
+
     elif test -f "$BERKELEY_DB_DIR/include/db.h";then
         case "$target_os" in
-        solaris*)  BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib -R$BERKELEY_DB_DIR/lib";;
+        solaris*)
+            #If we are staticlly linking the BDB files, we do not want a
+            #-R flag.  If .so's are present, assume we are dynamic linking
+            if test -n "`ls $BERKELEY_DB_DIR/lib/*.so 2>/dev/null`"
+            then
+                BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib -R$BERKELEY_DB_DIR/lib"
+            else
+                BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib"
+            fi;;
         *)         BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib";;
         esac
 
@@ -8440,6 +8498,7 @@ echo "$as_me: error: Cannot find BerkeleyDB" >&2;}
         BERKELEY_DB_LIB="-ldb"
         echo "$as_me:$LINENO: result: $BERKELEY_DB_DIR" >&5
 echo "${ECHO_T}$BERKELEY_DB_DIR" >&6
+
     elif test -d "$BERKELEY_DB_DIR"; then
 
         BERKELEY_DB_CFLAGS="-I$BERKELEY_DB_DIR/include"
@@ -8459,7 +8518,15 @@ echo "${ECHO_T}$BERKELEY_DB_DIR" >&6
         done
 
         case "$target_os" in
-        solaris*)  BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib -R$BERKELEY_DB_DIR/lib";;
+        solaris*)
+            #If we are staticlly linking the BDB files, we do not want a
+            #-R flag.  If .so's are present, assume we are dynamic linking
+            if test -n "`ls $BERKELEY_DB_DIR/lib/*.so 2>/dev/null`"
+            then
+                BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib -R$BERKELEY_DB_DIR/lib"
+            else
+                BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib"
+            fi;;
         *)         BERKELEY_DB_LDFLAGS="-L$BERKELEY_DB_DIR/lib";;
         esac
 
@@ -8691,18 +8758,18 @@ if test "${with_openssl+set}" = set; then
   withval="$with_openssl"
   OPENSSL_LIB_DIR=$with_openssl
 else
-  OPENSSL_LIB_DIR=yes
+  OPENSSL_LIB_DIR=default
 fi;
 echo "$as_me:$LINENO: checking for OpenSSL location" >&5
 echo $ECHO_N "checking for OpenSSL location... $ECHO_C" >&6
 if test x"$OPENSSL_LIB_DIR" = xno ; then
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-    { { echo "$as_me:$LINENO: error: This release of cfengine requires OpenSSL 0.9.6b or later" >&5
-echo "$as_me: error: This release of cfengine requires OpenSSL 0.9.6b or later" >&2;}
+    { { echo "$as_me:$LINENO: error: This release of cfengine requires OpenSSL 0.9.7 or later" >&5
+echo "$as_me: error: This release of cfengine requires OpenSSL 0.9.7 or later" >&2;}
    { (exit 1); exit 1; }; }
 else
-    if test x"$OPENSSL_LIB_DIR" = xyes ; then
+    if test x"$OPENSSL_LIB_DIR" = xdefault ; then
         for d in /opt/ssl /usr/local/ssl /usr/local /usr; do
             if test -f "$d/include/openssl/opensslv.h"; then
                 OPENSSL_LIB_LDFLAGS="-L$d/lib"
@@ -8720,7 +8787,15 @@ echo "$as_me: error: Cannot find OpenSSL" >&2;}
         fi
     elif test -f "$OPENSSL_LIB_DIR/include/openssl/ssl.h";then
         case "$target_os" in
-        solaris*)  OPENSSL_LIB_LDFLAGS="-L$OPENSSL_LIB_DIR/lib -R$OPENSSL_LIB_DIR/lib";;
+        solaris*)
+            #If we are staticlly linking the SSL files, we do not want a
+            #-R flag.  If .so's are present, assume we are dynamic linking
+            if test -n "`ls $OPENSSL_LIB_DIR/lib/*.so 2>/dev/null`"
+            then
+                OPENSSL_LIB_LDFLAGS="-L$OPENSSL_LIB_DIR/lib -R$OPENSSL_LIB_DIR/lib"
+            else
+                OPENSSL_LIB_LDFLAGS="-L$OPENSSL_LIB_DIR/lib"
+            fi;;
         *)         OPENSSL_LIB_LDFLAGS="-L$OPENSSL_LIB_DIR/lib";;
         esac
 
@@ -8792,8 +8867,8 @@ echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 ( exit $ac_status )
-{ { echo "$as_me:$LINENO: error: This release of cfengine requires openssl 0.9.6b or later" >&5
-echo "$as_me: error: This release of cfengine requires openssl 0.9.6b or later" >&2;}
+{ { echo "$as_me:$LINENO: error: This release of cfengine requires openssl 0.9.7 or later" >&5
+echo "$as_me: error: This release of cfengine requires openssl 0.9.7 or later" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -13342,6 +13417,22 @@ echo "$as_me:$LINENO: result: $rtry" >&5
 echo "${ECHO_T}$rtry" >&6
 
 
+lfsresult=no
+echo "$as_me:$LINENO: checking whether to compile with large file support" >&5
+echo $ECHO_N "checking whether to compile with large file support... $ECHO_C" >&6
+if test "$GETCONF" != "false"; then
+	lfscflags=`$GETCONF LFS_CFLAGS 2>/dev/null`
+	if test -n "$lfscflags"; then
+		CFLAGS="$CFLAGS $lfscflags"
+		lfsresult=yes
+	fi
+	lfsldflags=`$GETCONF LFS_LDFLAGS 2>/dev/null`
+	test -n "$lfsldflags" && LDFLAGS="$LDFLAGS $lfsldflags"
+fi
+echo "$as_me:$LINENO: result: $lfsresult" >&5
+echo "${ECHO_T}$lfsresult" >&6
+
+
 
 echo "$as_me:$LINENO: checking for main in -lpthread" >&5
 echo $ECHO_N "checking for main in -lpthread... $ECHO_C" >&6
@@ -16594,6 +16685,7 @@ s,@LATEX@,$LATEX,;t t
 s,@TEXI2DVI@,$TEXI2DVI,;t t
 s,@DVIPS@,$DVIPS,;t t
 s,@PS2PDF@,$PS2PDF,;t t
+s,@GETCONF@,$GETCONF,;t t
 s,@BERKELEY_DB_LDFLAGS@,$BERKELEY_DB_LDFLAGS,;t t
 s,@BERKELEY_DB_CFLAGS@,$BERKELEY_DB_CFLAGS,;t t
 s,@BERKELEY_DB_LIB@,$BERKELEY_DB_LIB,;t t
@@ -17342,8 +17434,8 @@ echo "$as_me: WARNING: " >&2;}
 echo "$as_me: WARNING: This version requires Berkeley db version 3.2 or" >&2;}
 { echo "$as_me:$LINENO: WARNING: later from www.sleepycat.com" >&5
 echo "$as_me: WARNING: later from www.sleepycat.com" >&2;}
-{ echo "$as_me:$LINENO: WARNING: This version requires OpenSSL 0.9.6b or later" >&5
-echo "$as_me: WARNING: This version requires OpenSSL 0.9.6b or later" >&2;}
+{ echo "$as_me:$LINENO: WARNING: This version requires OpenSSL 0.9.7 or later" >&5
+echo "$as_me: WARNING: This version requires OpenSSL 0.9.7 or later" >&2;}
 { echo "$as_me:$LINENO: WARNING: from www.openssl.org" >&5
 echo "$as_me: WARNING: from www.openssl.org" >&2;}
 { echo "$as_me:$LINENO: WARNING: " >&5
