Adding post factum version 2.1.13
git-svn-id: https://svn.iu.hio.no/projects/cfengine-2/trunk@18 0bacebff-10ef-0310-a86f-bc4055e020e4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1702,7 +1702,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=cfengine
- VERSION=2.1.12
+ VERSION=2.1.13
 
 
 cat >>confdefs.h <<_ACEOF
@@ -8328,7 +8328,7 @@ echo "$as_me: error: This release of cfengine requires BerkeleyDB 3.2 or later" 
 else
     if test "x$BERKELEY_DB_DIR" = "xdefault" ; then
         for v in BerkeleyDB.3.2 BerkeleyDB.3.3 BerkeleyDB.4.0  BerkeleyDB.4.1  BerkeleyDB.4.2 BerkeleyDB.4.3 BerkeleyDB.4.4; do
-            for d in /opt /usr/local /usr; do
+            for d in $prefix /opt /usr/local /usr; do
                 test -d "$d/$v" && BERKELEY_DB_DIR="$d/$v"
             done
         done
@@ -8336,7 +8336,7 @@ else
 
     if test "x$BERKELEY_DB_DIR" = "xdefault" ; then
 
-        for d in /opt /usr/local /usr; do
+        for d in $prefix /opt /usr/local /usr; do
             for v in db-4 db4 db3 db db40; do
 
                 if test -f "$d/include/$v/db.h" ; then
@@ -8348,6 +8348,10 @@ else
 		    # and libdb-4.0.a.  Debian has /usr/lib/libdb-4.1.a, for
 		    # instance.  Look for the appropriate library.
                     if test $v = db4 -o $v = db40; then
+			save_CFLAGS="$CFLAGS"
+			save_LDFLAGS="$LDFLAGS"
+			CFLAGS="$CFLAGS $BERKELEY_DB_CFLAGS"
+			LDFLAGS="$LDFLAGS $BERKELEY_DB_LDFLAGS"
 			echo "$as_me:$LINENO: checking for library containing db_create" >&5
 echo $ECHO_N "checking for library containing db_create... $ECHO_C" >&6
 if test "${ac_cv_search_db_create+set}" = set; then
@@ -8474,6 +8478,8 @@ if test "$ac_cv_search_db_create" != no; then
   BERKELEY_DB_LIB=$ac_cv_search_db_create
 fi
 
+			CFLAGS="$save_CFLAGS"
+			LDFLAGS="$save_LDFLAGS"
 		    else
                     	BERKELEY_DB_LIB="-l$v"
                     fi
@@ -8793,7 +8799,7 @@ echo "$as_me: error: This release of cfengine requires OpenSSL 0.9.7 or later" >
    { (exit 1); exit 1; }; }
 else
     if test x"$OPENSSL_LIB_DIR" = xdefault ; then
-        for d in /opt/ssl /usr/local/ssl /usr/local /usr; do
+        for d in $prefix /opt/ssl /usr/local/ssl /usr/local /usr; do
             if test -f "$d/include/openssl/opensslv.h"; then
                 OPENSSL_LIB_LDFLAGS="-L$d/lib"
                 OPENSSL_LIB_CPPFLAGS="-I$d/include"
@@ -8989,6 +8995,23 @@ echo $ECHO_N "checking pcre... $ECHO_C" >&6
 
         if test "x$withval" != "xno" ; then
             if test "x$withval" != "xyes" ; then
+                if test "x$withval" = "xdefault" ; then
+                    for d in $prefix /usr/local /usr; do
+                        if test -f "$d/include/pcreposix.h" ; then
+                            CPPFLAGS="$CPPFLAGS -I$d/include"
+                            LDFLAGS="$LDFLAGS -L$d/lib"
+                            PCRE_LIB="-lpcreposix"
+                            echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6 = "$d"
+                            break
+                        fi
+                    done
+                    if test x"$PCRE_LIB" = x ; then
+                        { { echo "$as_me:$LINENO: error: Cannot find PCRE" >&5
+echo "$as_me: error: Cannot find PCRE" >&2;}
+   { (exit 1); exit 1; }; }
+                    fi
+                else
                 if test -f "${withval}/include/pcreposix.h" ; then
                     CPPFLAGS="$CPPFLAGS -I${withval}/include"
                     LDFLAGS="$LDFLAGS -L${withval}/lib"
@@ -8998,6 +9021,7 @@ echo "${ECHO_T}" >&6 = "${withval}"
                     { { echo "$as_me:$LINENO: error: Cannot find PCRE" >&5
 echo "$as_me: error: Cannot find PCRE" >&2;}
    { (exit 1); exit 1; }; }
+                fi
                 fi
             else
                 echo "$as_me:$LINENO: result: " >&5
@@ -9839,7 +9863,8 @@ fi
 done
 
 
-for ac_header in malloc.h
+
+for ac_header in malloc.h sys/malloc.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
